SearchBarのバー追加とCSS修正
yukkoty/airb-training-React pull request #9
Opened 2021-12-01 09:32 UTC by yukkoty

SearchBarのバー（クリックしたら出てくる白い箱）
と、ボディのCSSを修正しました。
<img width="1440" alt="スクリーンショット 2021-12-01 18 31 34" src="https://user-images.githubusercontent.com/84750546/144208829-5d93b9d1-b024-4c0c-80e3-a7e506b62243.png">
<img width="1440" alt="スクリーンショット 2021-12-01 18 31 38" src="https://user-images.githubusercontent.com/84750546/144208833-e4540ddc-a712-4663-a9eb-66b2ffb26caa.png">

<img width="1440" alt="スクリーンショット 2021-12-01 18 31 31" src="https://user-images.githubusercontent.com/84750546/144208797-2797cae7-f630-4a63-a078-0305f60645ee.png">

2021-12-02 02:20 UTC, mikikun14 commented on src/LiveContent.js
> +                    </div>
この辺り写真に対して文字(ex: 自然に囲まれた宿泊先)が中央よせになってなさそうに見えますが、修正しなくていいですが？

2021-12-02 02:25 UTC, mikikun14 requested changes

2021-12-02 02:25 UTC, mikikun14 commented on src/SearchBar.css
> +    justify-content: flex-start;
このクラスってなんで必要なんでしたっけ？(僕が指示したこーどだったらごめんなさい)

2021-12-02 02:25 UTC, mikikun14 commented on src/SearchCheckin.js
>      )
チェックインとチェックアウトを押した時に出てくるそれぞれのカレンダーは、同じ見た目なので同じコンポーネントを使いまわすのが正しい気がしています(SearchCheckInとSearchCheckOutの両方はいらなさそう)

2021-12-03 04:42 UTC, yukkoty commented on src/SearchCheckin.js
>      )
なるほど！これ後々カレンダーを入れられればと思って別にしたんですが、同じ内容ならたしかに一緒で良さそうですね！

2021-12-03 04:45 UTC, yukkoty commented on src/SearchBar.css
> +    justify-content: flex-start;
これはみきやさんが指定してくださったんですが、クリックした要素のすぐ下に表示されるよう試みて指定してくれたものだと記憶してます。ただJSいじらないと結果動かないと仰ってたと思います！

2021-12-03 04:48 UTC, yukkoty commented on src/LiveContent.js
> +                    </div>
ほんとですね！直しました(๑╹ω╹๑ )

2021-12-03 04:51 UTC, merged